// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Template: main.rs.txt

use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::middleware::MetricsMiddleware;
use brrtrouter::router::Router;
use brrtrouter::runtime_config::RuntimeConfig;
use brrtrouter::server::AppService;
use brrtrouter::server::HttpServer;
use clap::Parser;
use pet_store::registry;
use std::collections::HashMap;
use std::io;
use std::path::PathBuf;

#[derive(Parser)]
struct Args {
    /// Path to the OpenAPI spec file
    #[clap(long, default_value = "openapi.yaml")]
    spec: PathBuf,

    /// HTTP Server port
    #[clap(long, default_value_t = 8080)]
    port: u16,

    /// Enable hot-reload of OpenAPI spec
    #[clap(long)]
    hot_reload: bool,

    /// Path to static files directory
    #[clap(long)]
    static_dir: Option<PathBuf>,

    /// Static files base path
    #[clap(long, default_value = "/static")]
    static_path: String,
}

fn main() -> io::Result<()> {
    let args = Args::parse();
    let runtime_config = RuntimeConfig::from_env();

    may::config().set_stack_size(runtime_config.stack_size);

    let spec_path = args.spec;
    let (routes, _slug) =
        brrtrouter::load_spec(spec_path.to_str().unwrap()).expect("Failed to load OpenAPI spec");

    let router = std::sync::Arc::new(std::sync::RwLock::new(Router::new(routes.clone())));
    let mut dispatcher = Dispatcher::new();

    // Register all handlers from the spec
    unsafe {
        registry::register_from_spec(&mut dispatcher, &routes);
    }

    // Add metrics middleware
    dispatcher.add_middleware(std::sync::Arc::new(MetricsMiddleware));

    // Create service
    let service = AppService::new(
        dispatcher,
        router.clone(),
        args.static_dir,
        args.static_path,
    );

    // Create and start HTTP server
    let server = HttpServer::new(service);
    server.run(("0.0.0.0", args.port))
}
