use brrtrouter::generator::{TemplateType, TemplateValidator, ValidationConfig, ValidationError};
use std::fs;
use tempfile::TempDir;

fn create_test_template(dir: &std::path::Path, name: &str, content: &str) -> std::path::PathBuf {
    let path = dir.join(name);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(&path, content).unwrap();
    path
}

#[test]
fn test_template_validation_successful_rust_template() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    let rust_template = r#"
// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.

use serde::{Deserialize, Serialize};
use crate::brrtrouter::typed::TypedHandlerRequest;

/// {{ handler_name }} handler implementation
#[derive(Debug)]
pub struct {{ struct_name }} {
    pub name: String,
    pub value: {{ field_type }},
}

impl Handler for {{ struct_name }} {
    type Request = Request;
    type Response = Response;

    fn handle(&self, req: TypedHandlerRequest<Self::Request>) -> anyhow::Result<Self::Response> {
        {% for field in response_fields %}
        let {{ field.name }} = {{ field.value }};
        {% endfor %}
        
        Ok(Response {
            {% for field in response_fields %}
            {{ field.name }},
            {% endfor %}
        })
    }
}
"#;

    create_test_template(&template_dir, "handler.rs.txt", rust_template);

    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let template_path = template_dir.join("handler.rs.txt");
    let result = validator.validate_template(&template_path);

    assert!(result.is_ok(), "Rust template validation should succeed");

    let metadata = result.unwrap();
    assert_eq!(metadata.template_type, TemplateType::Rust);
    assert!(metadata
        .required_variables
        .contains(&"handler_name".to_string()));
    assert!(metadata
        .required_variables
        .contains(&"struct_name".to_string()));
    assert!(metadata
        .required_variables
        .contains(&"field_type".to_string()));
    assert!(metadata
        .required_variables
        .contains(&"response_fields".to_string()));
}

#[test]
fn test_template_validation_toml_template() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    let toml_template = r#"
# ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
# This file is generated by BRRTRouter from OpenAPI specifications.

[package]
name = "{{ name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
brrtrouter = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }
"#;

    create_test_template(&template_dir, "Cargo.toml.txt", toml_template);

    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let template_path = template_dir.join("Cargo.toml.txt");
    let result = validator.validate_template(&template_path);

    assert!(result.is_ok(), "TOML template validation should succeed");

    let metadata = result.unwrap();
    assert_eq!(metadata.template_type, TemplateType::Toml);
    assert!(metadata.required_variables.contains(&"name".to_string()));
}

#[test]
fn test_template_validation_html_template() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    let html_template = r#"
<!-- ⚠️  AUTO-GENERATED CODE - DO NOT EDIT -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }} - BRRTRouter</title>
</head>
<body>
    <h1>{{ heading }}</h1>
    <p>Generated from: {{ spec_path }}</p>
    {% for item in items %}
    <div>{{ item.name }}: {{ item.value }}</div>
    {% endfor %}
</body>
</html>
"#;

    create_test_template(&template_dir, "index.html.txt", html_template);

    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let template_path = template_dir.join("index.html.txt");
    let result = validator.validate_template(&template_path);

    assert!(result.is_ok(), "HTML template validation should succeed");

    let metadata = result.unwrap();
    assert_eq!(metadata.template_type, TemplateType::Html);
    assert!(metadata.required_variables.contains(&"title".to_string()));
    assert!(metadata.required_variables.contains(&"heading".to_string()));
    assert!(metadata.required_variables.contains(&"items".to_string()));
}

#[test]
fn test_template_validation_syntax_errors() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    // Template with unclosed braces
    let bad_template1 = r#"
// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
use serde::Serialize;

pub struct {{ struct_name {
    pub name: String,
}
"#;

    create_test_template(&template_dir, "bad1.rs.txt", bad_template1);

    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let template_path = template_dir.join("bad1.rs.txt");
    let result = validator.validate_template(&template_path);

    assert!(
        result.is_err(),
        "Template with syntax errors should fail validation"
    );

    if let Err(ValidationError::SyntaxError(_)) = result {
        // Expected error type
    } else {
        panic!("Expected SyntaxError, got: {:?}", result);
    }

    // Template with nested expressions
    let bad_template2 = r#"
{{ outer {{ inner }} }}
"#;

    create_test_template(&template_dir, "bad2.rs.txt", bad_template2);
    let template_path2 = template_dir.join("bad2.rs.txt");
    let result2 = validator.validate_template(&template_path2);

    assert!(
        result2.is_err(),
        "Template with nested expressions should fail validation"
    );
}

#[test]
fn test_template_validation_missing_do_not_edit_warning() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    let rust_template_no_warning = r#"
use serde::{Deserialize, Serialize};

pub struct {{ struct_name }} {
    pub name: String,
}
"#;

    create_test_template(&template_dir, "no_warning.rs.txt", rust_template_no_warning);

    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let template_path = template_dir.join("no_warning.rs.txt");
    let result = validator.validate_template(&template_path);

    assert!(
        result.is_err(),
        "Rust template without DO NOT EDIT warning should fail validation"
    );

    if let Err(ValidationError::InvalidOutput(msg)) = result {
        assert!(msg.contains("DO NOT EDIT warning"));
    } else {
        panic!(
            "Expected InvalidOutput error about DO NOT EDIT warning, got: {:?}",
            result
        );
    }
}

#[test]
fn test_template_validation_all_templates() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    // Create multiple valid templates
    let rust_template = r#"
// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
use serde::Serialize;
pub struct {{ name }} {}
"#;

    let toml_template = r#"
# ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
[package]
name = "{{ name }}"
"#;

    let html_template = r#"
<!-- ⚠️  AUTO-GENERATED CODE - DO NOT EDIT -->
<!DOCTYPE html>
<html><head><title>{{ title }}</title></head></html>
"#;

    create_test_template(&template_dir, "handler.rs.txt", rust_template);
    create_test_template(&template_dir, "Cargo.toml.txt", toml_template);
    create_test_template(&template_dir, "index.html.txt", html_template);

    // Create one invalid template
    let bad_template = r#"
use serde::Serialize;
pub struct {{ unclosed
"#;
    create_test_template(&template_dir, "bad.rs.txt", bad_template);

    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let report = validator.validate_all().unwrap();

    assert_eq!(report.total_processed, 4);
    assert_eq!(report.success_count(), 3);
    assert_eq!(report.failure_count(), 1);
    assert!(!report.all_passed());
    assert_eq!(report.success_rate(), 75.0);

    // Check that the report summary is correct
    let summary = report.summary();
    assert!(summary.contains("3/4 passed"));
    assert!(summary.contains("75.0%"));
}

#[test]
fn test_template_validation_subdirectories() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    // Create templates in subdirectories
    let base_dir = template_dir.join("base");
    let components_dir = template_dir.join("components");
    fs::create_dir_all(&base_dir).unwrap();
    fs::create_dir_all(&components_dir).unwrap();

    let base_template = r#"
// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
use serde::Serialize;
pub struct {{ name }} {}
"#;

    let component_template = r#"
// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
impl TryFrom<HandlerRequest> for {{ request_type }} {
    type Error = anyhow::Error;
    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        {% for param in parameters %}
        let {{ param.name }} = req.{{ param.location }}_params.get("{{ param.name }}");
        {% endfor %}
        Ok(Self { })
    }
}
"#;

    create_test_template(&base_dir, "handler_base.rs.txt", base_template);
    create_test_template(
        &components_dir,
        "parameter_extraction.rs.txt",
        component_template,
    );

    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let report = validator.validate_all().unwrap();

    assert_eq!(report.total_processed, 2);
    assert_eq!(report.success_count(), 2);
    assert!(report.all_passed());
}

#[test]
fn test_template_validation_configuration() {
    let temp_dir = TempDir::new().unwrap();
    let template_dir = temp_dir.path().join("templates");
    fs::create_dir_all(&template_dir).unwrap();

    let large_template = "a".repeat(2048); // 2KB template
    create_test_template(&template_dir, "large.rs.txt", &large_template);

    // Test with size limit
    let config = ValidationConfig {
        template_dir: template_dir.clone(),
        max_template_size: 1024, // 1KB limit
        ..Default::default()
    };
    let mut validator = TemplateValidator::new(config);

    let template_path = template_dir.join("large.rs.txt");
    let result = validator.validate_template(&template_path);

    assert!(
        result.is_err(),
        "Template exceeding size limit should fail validation"
    );

    if let Err(ValidationError::InvalidOutput(msg)) = result {
        assert!(msg.contains("exceeds maximum"));
    } else {
        panic!(
            "Expected InvalidOutput error about size limit, got: {:?}",
            result
        );
    }
}

#[test]
fn test_template_type_detection() {
    assert_eq!(
        TemplateType::from_path(std::path::Path::new("test.rs")),
        TemplateType::Rust
    );
    assert_eq!(
        TemplateType::from_path(std::path::Path::new("test.toml")),
        TemplateType::Toml
    );
    assert_eq!(
        TemplateType::from_path(std::path::Path::new("test.html")),
        TemplateType::Html
    );
    assert_eq!(
        TemplateType::from_path(std::path::Path::new("handler.rs.txt")),
        TemplateType::Rust
    );
    assert_eq!(
        TemplateType::from_path(std::path::Path::new("config.toml.txt")),
        TemplateType::Toml
    );
    assert_eq!(
        TemplateType::from_path(std::path::Path::new("unknown.xyz")),
        TemplateType::Unknown
    );
}

#[test]
fn test_validation_error_display() {
    let errors = vec![
        ValidationError::TemplateNotFound(std::path::PathBuf::from("missing.rs")),
        ValidationError::SyntaxError("Bad syntax".to_string()),
        ValidationError::MissingVariables(vec!["var1".to_string(), "var2".to_string()]),
        ValidationError::CompilationError("Failed to compile".to_string()),
        ValidationError::GeneratedCodeError("Code error".to_string()),
        ValidationError::InvalidOutput("Invalid output".to_string()),
    ];

    for error in errors {
        let display = format!("{}", error);
        assert!(!display.is_empty(), "Error display should not be empty");

        // Check that error type is reflected in the message
        match error {
            ValidationError::TemplateNotFound(_) => assert!(display.contains("not found")),
            ValidationError::SyntaxError(_) => assert!(display.contains("syntax error")),
            ValidationError::MissingVariables(_) => assert!(display.contains("Missing")),
            ValidationError::CompilationError(_) => assert!(display.contains("compilation")),
            ValidationError::GeneratedCodeError(_) => assert!(display.contains("Generated code")),
            ValidationError::InvalidOutput(_) => assert!(display.contains("Invalid")),
        }
    }
}
