// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Template: registry.rs.txt


// Auto-generated handler registry for OpenAPI endpoints
use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed;

/// Register all handlers with the dispatcher
/// 
/// This function registers all handlers defined in the OpenAPI specification
/// with the dispatcher. Each handler is registered with its corresponding
/// route metadata and typed handler function.
/// 
/// # Safety
/// This function is unsafe because it registers handlers with the dispatcher
/// which may involve raw pointer operations or other unsafe operations.
pub unsafe fn register_all(dispatcher: &mut Dispatcher) {
    dispatcher.register_typed(
        "admin_settings",
        spawn_typed::<crate::handlers::admin_settings::Request, crate::handlers::admin_settings::Response, _>(
            crate::handlers::admin_settings::admin_settings
        ),
    );
    dispatcher.register_typed(
        "stream_events",
        spawn_typed::<crate::handlers::stream_events::Request, crate::handlers::stream_events::Response, _>(
            crate::handlers::stream_events::stream_events
        ),
    );
    dispatcher.register_typed(
        "get_item",
        spawn_typed::<crate::handlers::get_item::Request, crate::handlers::get_item::Response, _>(
            crate::handlers::get_item::get_item
        ),
    );
    dispatcher.register_typed(
        "post_item",
        spawn_typed::<crate::handlers::post_item::Request, crate::handlers::post_item::Response, _>(
            crate::handlers::post_item::post_item
        ),
    );
    dispatcher.register_typed(
        "list_pets",
        spawn_typed::<crate::handlers::list_pets::Request, crate::handlers::list_pets::Response, _>(
            crate::handlers::list_pets::list_pets
        ),
    );
    dispatcher.register_typed(
        "add_pet",
        spawn_typed::<crate::handlers::add_pet::Request, crate::handlers::add_pet::Response, _>(
            crate::handlers::add_pet::add_pet
        ),
    );
    dispatcher.register_typed(
        "get_pet",
        spawn_typed::<crate::handlers::get_pet::Request, crate::handlers::get_pet::Response, _>(
            crate::handlers::get_pet::get_pet
        ),
    );
    dispatcher.register_typed(
        "list_users",
        spawn_typed::<crate::handlers::list_users::Request, crate::handlers::list_users::Response, _>(
            crate::handlers::list_users::list_users
        ),
    );
    dispatcher.register_typed(
        "get_user",
        spawn_typed::<crate::handlers::get_user::Request, crate::handlers::get_user::Response, _>(
            crate::handlers::get_user::get_user
        ),
    );
    dispatcher.register_typed(
        "list_user_posts",
        spawn_typed::<crate::handlers::list_user_posts::Request, crate::handlers::list_user_posts::Response, _>(
            crate::handlers::list_user_posts::list_user_posts
        ),
    );
    dispatcher.register_typed(
        "get_post",
        spawn_typed::<crate::handlers::get_post::Request, crate::handlers::get_post::Response, _>(
            crate::handlers::get_post::get_post
        ),
    );
    }

/// Register all routes from OpenAPI specification with the dispatcher
/// 
/// This function processes the routes loaded from the OpenAPI specification
/// and registers the corresponding handlers with the dispatcher.
/// 
/// # Safety
/// This function is unsafe because it calls register_all which involves
/// unsafe operations during handler registration.
pub unsafe fn register_from_spec(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    register_all(dispatcher);
}