"""Tiltfile generation for BRRTRouter-based projects.

Single pattern: parse bff-suite-config.yaml for service discovery, then render
the standard Tiltfile sections. Works for RERP, PriceWhisperer, Hauliage, etc.

Usage:
    from brrtrouter_tooling.workspace.tilt.tilt_gen import generate_tiltfile
    tiltfile = generate_tiltfile(config)
    Path("Tiltfile").write_text(tiltfile)
"""

from __future__ import annotations

from typing import Any

# Tiltfile uses %% for literal % at runtime.
# We build strings with f-strings/format() so Python's % operator never
# conflicts with Tiltfile's % operators.
_TILT_FMT = "%s"  # Placeholder we use in Tiltfile code (literal in output)


def generate_tiltfile(config: dict[str, Any]) -> str:
    parts: list[str] = []
    _render_header(parts, config)
    _render_discovery(parts, config)
    _render_helpers(parts, config)
    _render_service_blocks(parts, config)
    _render_bff(parts, config)
    _render_custom_blocks(parts, config)
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# String builders — avoid Python % operator to never conflict with Tiltfile %
# ---------------------------------------------------------------------------

_DQ = '"'  # double quote
_BS = "\\"  # backslash
_BSDQ = "\\" + _DQ  # \"
_BSBS = "\\\\"  # \\


def _w(parts: list[str], line: str) -> None:
    parts.append(line)


def _fmt(parts: list[str], template: str, *args: Any) -> None:
    """Format a Tiltfile line using positional .format().
    Tiltfile uses %% for literal % at runtime.
    This helper takes a template with {0}, {1}... and fills them in.
    The result is a Python string that, when written, contains the literal %%s etc.
    """
    parts.append(template.format(*args))


# ---------------------------------------------------------------------------
# Header: config, env vars, tooling install, k8s namespaces
# ---------------------------------------------------------------------------


def _render_header(parts: list[str], config: dict[str, Any]) -> None:
    pname = config["project_name"]
    cli_name = config.get("cli_name", "brrtrouter")
    brrt_rel = config.get("brrtrouter_rel_path", "../BRRTRouter")
    brrt_venv = config.get("brrtrouter_venv", "~/.local/share/brrtrouter/venv")
    brrt_root = config["brrtrouter_root"]
    wrapped = cli_name != "brrtrouter"

    port = "10351" if not wrapped else "10350"
    ns = f"kind-{pname}"
    root_env = "BRRTRouter_ROOT" if not wrapped else "BRRTROUTER_ROOT"
    venv_env = "BRRTRouter_VENV" if not wrapped else "BRRTROUTER_VENV"
    cli_venv_name = cli_name if not wrapped else pname

    _w(parts, f"# {pname} Development Environment")
    _w(parts, "# Auto-generated by photon — do not edit manually")
    _w(parts, "")
    _w(parts, f"allow_k8s_contexts(['{ns}'])")
    _w(parts, "")
    _w(parts, "update_settings(k8s_upsert_timeout_secs=60)")
    _w(parts, "")
    _w(parts, "docker_prune_settings(")
    _w(parts, "    disable=False,")
    _w(parts, "    max_age_mins=30,")
    _w(parts, "    keep_recent=1,")
    _w(parts, "    interval_hrs=1")
    _w(parts, ")")
    _w(parts, "")
    _w(parts, "config.define_string('tilt_port', args=False, usage='Port for Tilt web UI')")
    _w(parts, "cfg = config.parse()")
    _w(parts, f"tilt_port = cfg.get('tilt_port', '{port}')")
    _w(parts, "os.putenv('TILT_PORT', tilt_port)")
    _w(parts, "")

    # BRRTRouter root
    _w(parts, f"_brrtrouter_env = os.getenv('{root_env}', '').strip().rstrip('/')")
    _w(parts, f"brrtrouter_root = _brrtrouter_env if _brrtrouter_env else '{brrt_rel}'")
    _w(parts, "")

    # BRRTRouter venv
    _w(parts, f"_brrtrouter_venv_env = os.getenv('{venv_env}', '').strip().rstrip('/')")
    _w(parts, "_home = os.getenv('HOME', '') or os.getenv('USERPROFILE', '')")
    _w(
        parts,
        "brrtrouter_venv = _brrtrouter_venv_env if _brrtrouter_venv_env else (_home + '/.local/share/brrtrouter/venv' if _home else '.local/share/brrtrouter/venv')",
    )

    # Variable names for CLI binaries - use project name for wrapped projects
    if wrapped:
        _w(parts, f"{cli_name}_bin = '{cli_venv_name}/bin/{cli_name}' % brrtrouter_venv")
        _w(
            parts,
            f"{cli_name}_gen_bin = '{cli_venv_name}/target/debug/brrtrouter-gen' % brrtrouter_root",
        )
        # Keep alias for backward compat
        _w(parts, f"brrtrouter_bin = {cli_name}_bin")
        _w(parts, f"brrtrouter_gen_bin = {cli_name}_gen_bin")
    else:
        _w(parts, f"brrtrouter_bin = '{cli_venv_name}/bin/brrtrouter' % brrtrouter_venv")
        _w(
            parts,
            f"brrtrouter_gen_bin = '{cli_venv_name}/target/debug/brrtrouter-gen' % brrtrouter_root",
        )
    _w(parts, "")

    # Wrapped CLI binary — already handled above in header block

    # Tooling ignore
    _w(parts, "TOOLING_IGNORE = [")
    for p in [
        "**/*.pyc",
        "**/*.pyo",
        "**/__pycache__",
        "**/.pytest_cache",
        "**/.coverage",
        "**/.coverage.*",
        "**/htmlcov",
        "**/coverage.xml",
        "**/.ruff_cache",
        "**/.mypy_cache",
        "**/*.egg",
        "**/*.egg-info",
        "**/*.egg-info/**",
        "**/brrtrouter_tooling.egg-info/**",
        "**/*_tooling.egg-info/**",
        "**/build",
        "**/build/**",
        "**/.hypothesis",
        "**/.DS_Store",
    ]:
        _w(parts, f"    '{p}',")
    _w(parts, "]")
    _w(parts, "")

    # Tooling install
    _w(parts, "local_resource(")
    _w(parts, "    'build-tooling',")
    _w(parts, "    '''")
    _w(parts, "set -e")
    _w(parts, f'VENV="{brrt_venv}"')
    _w(parts, f'BRRROOT="{brrt_root}"')
    _w(parts, 'test -d "$VENV" || python3 -m venv "$VENV"')
    _w(parts, '"$VENV/bin/pip" install -U pip')
    _w(parts, '"$VENV/bin/pip" install -e "$BRRROOT/tooling[dev]"')
    _w(parts, "cd tooling && \"$VENV/bin/pip\" install -e '[dev]'")
    _w(parts, "    '''")
    _w(parts, "    deps=[")
    _w(parts, "        './tooling/pyproject.toml',")
    _w(parts, f"        '{brrt_rel}/tooling/pyproject.toml' %% brrtrouter_root,")
    _w(parts, "    ],")
    _w(parts, "    ignore=TOOLING_IGNORE,")
    _w(parts, "    labels=['tooling'],")
    _w(parts, "    allow_parallel=True,")
    _w(parts, ")")
    _w(parts, "")

    # K8s namespaces
    _w(parts, "k8s_yaml(kustomize('./k8s/data'))")
    _w(parts, "k8s_yaml(kustomize('./k8s/microservices'))")
    _w(parts, "")


# ---------------------------------------------------------------------------
# Discovery: parse bff-suite-config.yaml
# ---------------------------------------------------------------------------


def _render_discovery(parts: list[str], config: dict[str, Any]) -> None:
    pname = config["project_name"]
    suite = config["suite_name"]
    upper = suite.upper().replace("-", "_")
    config_path = config.get("suite_config_path", f"openapi/{suite}/bff-suite-config.yaml")

    _w(parts, "# === Service Discovery ===")
    _w(parts, "")

    # _unquote
    _w(parts, "def _unquote(val):")
    _w(parts, "    val = val.strip()")
    _w(
        parts,
        "    if (val.startswith('" + _DQ + "') and val.endswith('" + _DQ + "')) or "
        "(val.startswith('" + chr(39) + "') and val.endswith('" + chr(39) + "')):",
    )
    _w(parts, "        return val[1:-1]")
    _w(parts, "    return val")
    _w(parts, "")

    # _parse_bff_suite_config
    _w(parts, "def _parse_bff_suite_config(path):")
    _w(parts, "    content = str(read_file(path))")
    _w(parts, "    services = []")
    _w(parts, "    service_ports = {}")
    _w(parts, "    service_spec_paths = {}")
    _w(parts, "    bff_service_name = 'bff'")
    _w(parts, "    in_services = False")
    _w(parts, "    current = None")
    _w(parts, "")
    _w(parts, f"    for raw in content.split('{_BSBS}n'):")
    _w(parts, "        stripped = raw.strip()")
    _w(parts, "        if not stripped or stripped.startswith('#'):")
    _w(parts, "            continue")
    _w(parts, "")
    _w(parts, "        if stripped.startswith('bff_service_name:'):")
    _w(parts, "            bff_service_name = _unquote(stripped.split(':', 1)[1])")
    _w(parts, "            continue")
    _w(parts, "")
    _w(parts, "        if stripped == 'services:':")
    _w(parts, "            in_services = True")
    _w(parts, "            current = None")
    _w(parts, "            continue")
    _w(parts, "")
    _w(parts, "        if in_services and not raw.startswith('  '):")
    _w(parts, "            in_services = False")
    _w(parts, "            current = None")
    _w(parts, "")
    _w(parts, "        if not in_services:")
    _w(parts, "            continue")
    _w(parts, "")
    _w(
        parts,
        "        if raw.startswith('  ') and not raw.startswith('    ') and stripped.endswith(':'):",
    )
    _w(parts, "            current = stripped[:-1]")
    _w(parts, "            services.append(current)")
    _w(parts, "            continue")
    _w(parts, "")
    _w(parts, "        if current and raw.startswith('    ') and stripped.startswith('port:'):")
    _w(parts, "            service_ports[current] = _unquote(stripped.split(':', 1)[1])")
    _w(parts, "            continue")
    _w(parts, "")
    _w(
        parts,
        "        if current and raw.startswith('    ') and stripped.startswith('spec_path:'):",
    )
    _w(parts, "            service_spec_paths[current] = _unquote(stripped.split(':', 1)[1])")
    _w(parts, "            continue")
    _w(parts, "")
    _w(parts, "    return {")
    _w(parts, "        'bff_service_name': bff_service_name,")
    _w(parts, "        'services': services,")
    _w(parts, "        'ports': service_ports,")
    _w(parts, "        'spec_paths': service_spec_paths,")
    _w(parts, "    }")
    _w(parts, "")

    # Parse
    _w(parts, f"SUITE_CONFIG = _parse_bff_suite_config('{config_path}')")
    _w(parts, f"DISCOVERED_{upper}_SERVICES = SUITE_CONFIG['services']")
    _w(parts, f"{upper}_PORTS = SUITE_CONFIG['ports']")
    _w(parts, f"{upper}_SPEC_PATHS = SUITE_CONFIG['spec_paths']")
    _w(parts, f"{upper}_BFF_NAME = SUITE_CONFIG['bff_service_name']")

    # Apply port overrides from JSON config (authoritative, overrides YAML ports).
    # The JSON config is built from photon.toml [ports] which is the global registry.
    _w(parts, "")
    _w(parts, "def _apply_port_overrides(config: dict) -> None:")
    _w(parts, '    """Overlay port assignments from JSON config onto YAML-discovered ports."""')
    _w(parts, "    svc_overrides = config.get('services', [])")
    _w(parts, "    if not svc_overrides:")
    _w(parts, "        return")
    _w(parts, "    svc_map = {s['name']: s for s in svc_overrides}")
    _w(parts, f"    for svc_name in {upper}_PORTS:")
    _w(parts, "        if svc_name in svc_map:")
    _w(parts, "            override_port = svc_map[svc_name].get('port')")
    _w(parts, "            if override_port and override_port != " + upper + "_PORTS[svc_name]:")
    _w(parts, f"                {upper}_PORTS[svc_name] = override_port")
    _w(parts, "")
    _w(parts, "_apply_port_overrides(config)")
    _w(parts, "")

    # Runtime readiness
    _w(parts, "def _runtime_ready_service(name):")
    _w(
        parts,
        f"    return str(local('test -d ./microservices/{suite}/$_s/gen/src && test -d ./microservices/{suite}/$_s/impl/src && echo yes || true' % '{suite}', quiet=True)).strip() == 'yes'",
    )
    _w(parts, "")
    _w(parts, f"_{upper}_SERVICES_READY = []")
    _w(parts, f"_{upper}_SERVICES_CONTRACT = []")
    _w(parts, f"for _s in DISCOVERED_{upper}_SERVICES:")
    _w(parts, "    if _runtime_ready_service(_s):")
    _w(parts, f"        _{upper}_SERVICES_READY.append(_s)")
    _w(parts, "    else:")
    _w(parts, f"        _{upper}_SERVICES_CONTRACT.append(_s)")
    _w(parts, "")
    _w(
        parts,
        f'print("{pname} Tilt discovered %d %s service contracts from %s" %% (len(DISCOVERED_{upper}_SERVICES), "{upper}", "{suite}", SUITE_CONFIG))',
    )
    _w(
        parts,
        f'print("{pname} Tilt runtime-ready %s services: %s" %% (len(_{upper}_SERVICES_READY), ", ".join(_{upper}_SERVICES_READY)))',
    )
    _w(parts, f"if _{upper}_SERVICES_CONTRACT:")
    _w(
        parts,
        f'    print("{pname} Tilt contract-only %s services skipped: %s" %% ("{suite}", ", ".join(_{upper}_SERVICES_CONTRACT)))',
    )
    _w(parts, "")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _render_helpers(parts: list[str], config: dict[str, Any]) -> None:
    suite = config["suite_name"]
    pname = config["project_name"]
    cli_name = config.get("cli_name", "brrtrouter")
    wrapped = cli_name != "brrtrouter"
    upper = suite.upper().replace("-", "_")
    gen_bin = f"{pname}_bin" if wrapped else "brrtrouter_gen_bin"

    _w(parts, "# === Helper functions ===")
    _w(parts, "")

    # get_service_port
    _w(parts, "def get_service_port(name):")
    _w(parts, f"    if name in {upper}_PORTS:")
    _w(parts, f"        return {upper}_PORTS[name]")
    _w(parts, "    return '8080'")
    _w(parts, "")

    # get_package_name
    _w(parts, "def get_package_name(name):")
    if wrapped:
        _w(parts, f"    fallback_pkg = 'rerp_{suite}_' % ('{suite}') + name.replace('-', '_')")
    else:
        _w(
            parts,
            f"    fallback_pkg = '{pname}_{suite}_' % (pname, '{pname}') + name.replace('-', '_')",
        )
    if wrapped:
        _w(parts, f"    manifest = 'microservices/{suite}/%s/impl/Cargo.toml' % name")
    else:
        _w(parts, "    manifest = 'microservices/%s/impl/Cargo.toml' % name")
    _w(
        parts,
        f"    if str(local('test -e {_BSDQ}%s{_BSDQ} && echo yes || true' % manifest, quiet=True)).strip() != 'yes':",
    )
    _w(parts, "        return fallback")
    _w(parts, "")
    _w(parts, "    content = str(read_file(manifest))")
    _w(parts, "    in_package = False")
    _w(parts, f"    for raw in content.split('{_BSBS}n'):")
    _w(parts, "        stripped = raw.strip()")
    _w(parts, "        if stripped == '[package]':")
    _w(parts, "            in_package = True")
    _w(parts, "            continue")
    _w(parts, "        if stripped.startswith('[') and stripped != '[package]':")
    _w(parts, "            in_package = False")
    _w(parts, "            continue")
    _w(parts, '        if in_package and stripped.startswith("name = "):')
    _w(
        parts,
        f"            return stripped.split('=', 1)[1].strip().strip('{_DQ}').strip('{chr(39)}')",
    )
    _w(parts, "    return fallback")
    _w(parts, "")

    # get_binary_name (PW only)
    if not wrapped:
        _w(parts, "def get_binary_name(name):")
        _w(parts, "    if name in BINARY_NAMES:")
        _w(parts, "        return BINARY_NAMES[name]")
        _w(parts, "    return name.replace('-', '_') + '_impl'")
        _w(parts, "")

    # create_microservice_lint
    _w(parts, "def create_microservice_lint(name, spec_file):")
    _w(parts, "    local_resource(")
    _w(parts, "        '%s-lint' % name,")
    _w(parts, "        cmd='''")
    lint_lines = [
        "            set -e",
        '            echo "🔍 Linting %s OpenAPI spec..." % name',
        f"            {gen_bin} lint {_BSDQ}",
        f"                --spec ./openapi/{suite}/%s {_BSDQ} % (spec_file, spec_file)",
        "                --fail-on-error || \\",
        "            cargo run --manifest-path "
        + "brrtrouter_root/Cargo.toml --bin brrtrouter-gen -- \\",
        "                lint \\",
        f"                --spec ./openapi/{suite}/%s {_BSDQ} % (spec_file, spec_file)",
        "                --fail-on-error",
        '            echo "✅ %s OpenAPI spec linting passed" % name',
    ]
    _w(parts, "\n".join(lint_lines))
    _w(parts, "        '''")
    _w(parts, "        deps=['./openapi/%s/%s' % (suite, spec_file)],")
    _w(parts, "        resource_deps=[],")
    _w(parts, f"        labels=['{pname}_' + name],")
    _w(parts, "        allow_parallel=True,")
    _w(parts, "    )")
    _w(parts, "")

    # create_microservice_gen
    if wrapped:
        gen_cmd = f"{pname} gen suite %s --service %s" % (suite, "name")
    else:
        gen_cmd = (
            f"{cli_name} client gen suite %s --service %s --openapi-dir microservices/openapi"
            % (suite, "name")
        )
    _w(parts, "def create_microservice_gen(name, spec_file, output_dir):")
    _w(parts, "    local_resource(")
    _w(parts, "        '%s-service-gen' % name,")
    _w(parts, f"        cmd='{gen_cmd}'")
    _w(parts, "        deps=[")
    _w(parts, "            './openapi/%s/%s' % (suite, spec_file),")
    _w(parts, "            'tooling/pyproject.toml',")
    _w(parts, "        ],")
    _w(parts, "        ignore=[")
    for section in ["gen/src", "gen/doc", "impl/config", "gen/static_site"]:
        _w(parts, f"            './microservices/{suite}/%s/{section}' % name,")
    _w(parts, "        ],")
    _w(parts, "        resource_deps=['%s-lint' % name],")
    _w(parts, f"        labels=['{pname}_' + name],")
    _w(parts, "        allow_parallel=True,")
    _w(parts, "    )")
    _w(parts, "")

    # create_microservice_build_resource
    if wrapped:
        build_cmd = f"{pname} build microservice %s" % "name"
    else:
        build_cmd = f"{cli_name} client build microservice %s" % "name"
    _w(parts, "def create_microservice_build_resource(name):")
    _w(parts, "    local_resource(")
    _w(parts, "        'build-%s' % name,")
    _w(parts, f"        cmd='{build_cmd}'")
    _w(parts, "        deps=[")
    for section in ["gen/Cargo.toml", "impl/Cargo.toml", "gen/src", "impl/src"]:
        _w(parts, f"            './microservices/{suite}/%s/{section}' % name,")
    _w(parts, "            'tooling/pyproject.toml',")
    _w(parts, "        ],")
    _w(parts, "        ignore=[")
    _w(parts, "            './microservices/target',")
    _w(parts, "            './build_artifacts',")
    _w(parts, "        ],")
    _w(parts, f"        resource_deps=['%s-{suite}-all-gens']" % pname)
    _w(parts, f"        labels=['{pname}_' + name],")
    _w(parts, "        allow_parallel=True,")
    _w(parts, "    )")
    _w(parts, "")

    # create_microservice_deployment
    prefix = (
        config["docker_image_prefix"].split("%")[0]
        if "%" in config["docker_image_prefix"]
        else config["docker_image_prefix"]
    )
    if wrapped:
        copy_cmd = f"{pname} docker copy-binary %s %s %s" % (
            "target_path",
            "artifact_path",
            "binary_name",
        )
        docker_cmd = f"{pname} docker build-image-simple %s %s %s --service %s" % (
            "image_name",
            "hash_path",
            "artifact_path",
            "name",
        )
    else:
        copy_cmd = f"{cli_name} docker copy-binary %s %s %s" % (
            "target_path",
            "artifact_path",
            "binary_name",
        )
        docker_cmd = f"{cli_name} docker build-image-simple %s %s %s --service %s" % (
            "image_name",
            "hash_path",
            "artifact_path",
            "name",
        )

    _w(parts, "def create_microservice_deployment(name):")
    _w(parts, "    package_name = get_package_name(name)")
    if wrapped:
        _w(parts, "    binary_name = name.replace('-', '_')")
    else:
        _w(parts, "    binary_name = get_binary_name(name)")
    _w(
        parts,
        f"    target_path = 'microservices/target/{config['target_rust_triple']}/debug/%s' % package_name",
    )
    _w(parts, "    artifact_path = 'build_artifacts/%s' % binary_name")
    _w(parts, f"    image_name = '{prefix}-%s' % name")
    _w(parts, "    port = get_service_port(name)")
    _w(parts, "")
    _w(parts, "    hash_path = 'build_artifacts/%s.sha256' % binary_name")
    _w(parts, "    local_resource(")
    _w(parts, "        'copy-%s' % name,")
    _w(parts, f"        cmd='{copy_cmd}'")
    _w(parts, "        deps=[target_path, 'tooling/pyproject.toml'],")
    _w(parts, "        resource_deps=['build-%s' % name],")
    _w(parts, f"        labels=['{pname}_' + name],")
    _w(parts, "        allow_parallel=True,")
    _w(parts, "    )")
    _w(parts, "")
    _w(parts, "    local_resource(")
    _w(parts, "        'docker-%s' % name,")
    _w(parts, f"        cmd='{docker_cmd}'")
    _w(
        parts,
        "        deps=[hash_path, artifact_path, 'docker/microservices/Dockerfile.template', 'tooling/pyproject.toml'],",
    )
    _w(parts, "        resource_deps=['copy-%s' % name],")
    _w(parts, f"        labels=['{pname}_' + name],")
    _w(parts, "        allow_parallel=False,")
    _w(parts, "    )")
    _w(parts, "")

    helm_values = "'{}/values/{}.yaml' % ('{}', name)".format(
        config["helm_chart_path"], config["helm_chart_path"], "name"
    )
    _w(
        parts,
        "    k8s_yaml(helm('{}' % '{}', name=name, namespace='{}', values=[{}]))".format(
            config["helm_chart_path"], config["helm_chart_path"], pname, helm_values
        ),
    )
    _w(parts, "")
    _w(parts, "    k8s_resource(")
    _w(parts, "        name,")
    _w(parts, "        port_forwards=['%s:%s' % (port, port)],")
    _w(parts, "        resource_deps=['{}-database-env', 'docker-{}'],".format(pname, "name"))
    _w(parts, f"        labels=['{pname}_' + name],")
    _w(parts, "        auto_init=True,")
    _w(parts, "    )")
    _w(parts, "")


# ---------------------------------------------------------------------------
# Service blocks + BFF
# ---------------------------------------------------------------------------


def _render_service_blocks(parts: list[str], config: dict[str, Any]) -> None:
    pname = config["project_name"]
    suite = config["suite_name"]
    wrapped = config.get("cli_name", "brrtrouter") != "brrtrouter"
    upper = suite.upper().replace("-", "_")

    _w(parts, "# === Service Code Generation ===")
    _w(parts, "")
    _w(parts, "local_resource(")
    _w(parts, f"    '{pname}-{suite}-all-gens' % pname,")
    _w(parts, f'    "echo \\"{pname} All {suite} codegen complete\\"" % pname,')
    if wrapped:
        _w(
            parts,
            f"    resource_deps=['%s-service-gen' % name for name in DISCOVERED_{upper}_SERVICES],",
        )
    else:
        _w(parts, f"    resource_deps=['%s-service-gen' % name for name in {upper}_SERVICES],")
    _w(parts, f"    labels=['{pname}_all_gens']")
    _w(parts, "    allow_parallel=False,")
    _w(parts, ")")
    _w(parts, "")

    if wrapped:
        spec_helper = f"'{suite}/%s' % {upper}_SPEC_PATHS.get(name, '%s/openapi.yaml' % name)"
        svc = f"DISCOVERED_{upper}_SERVICES"
    else:
        spec_helper = "'%s/openapi.yaml' % name"
        svc = f"{upper}_SERVICES"
    _w(parts, f"for name in {svc}:")
    _w(parts, f"    service_spec_file = {spec_helper}")
    _w(parts, "    create_microservice_lint(name, service_spec_file)")
    _w(parts, "    create_microservice_gen(name, service_spec_file, name)")
    if not wrapped:
        _w(parts, "    # create_microservice_stubs_resource(name, service_spec_file)")
        _w(parts, "    # create_microservice_test_resource(name)")
    _w(parts, "    create_microservice_build_resource(name)")
    _w(parts, "    create_microservice_deployment(name)")
    _w(parts, "")


# ---------------------------------------------------------------------------
# BFF
# ---------------------------------------------------------------------------


def _render_bff(parts: list[str], config: dict[str, Any]) -> None:
    pname = config["project_name"]
    suite = config["suite_name"]
    wrapped = config.get("cli_name", "brrtrouter") != "brrtrouter"

    if not config.get("has_bff", False):
        return

    _w(parts, "# === BFF (Backend for Frontend) ===")
    _w(parts, "")

    bff_name = config.get("bff_service_name", "bff")
    bff_spec = f"openapi/{suite}/openapi_bff.yaml" if wrapped else "openapi/bff/openapi_bff.yaml"

    if wrapped:
        bff_cmds = [
            "        set -e",
            f'        echo "🔄 Regenerating {suite} BFF OpenAPI spec..."',
            f"        {pname} bff generate-system --suite {suite}",
            '        echo "✅ BFF spec regeneration complete"',
        ]
    else:
        bff_cmds = [
            "        set -e",
            f'        echo "🔄 Regenerating {suite} BFF OpenAPI spec..."',
            f"        {pname} client gen suite bff --service traderBFF",
            '        echo "✅ BFF spec regeneration complete"',
        ]

    _w(parts, "local_resource(")
    _w(parts, "    'bff-spec-gen',")
    _w(parts, "    cmd='''")
    _w(parts, "\n".join(bff_cmds))
    _w(parts, "    '''")
    _w(parts, "    deps=['./openapi/%s/bff-suite-config.yaml' %% suite],")
    _w(parts, f"    ignore=['.{bff_spec}']")
    _w(parts, f"    labels=['{pname}_bff']")
    _w(parts, "    allow_parallel=True,")
    _w(parts, ")")
    _w(parts, "")

    _w(parts, f"create_microservice_gen('{bff_name}', '{bff_spec}', '{bff_name}')")
    _w(parts, f"create_microservice_build_resource('{bff_name}')")
    _w(parts, f"create_microservice_deployment('{bff_name}')")
    _w(parts, "")


# ---------------------------------------------------------------------------
# Custom blocks
# ---------------------------------------------------------------------------


def _render_custom_blocks(parts: list[str], config: dict[str, Any]) -> None:
    custom = config.get("custom_blocks", [])
    if custom:
        _w(parts, "# === Project-Specific Blocks ===")
        _w(parts, "")
        for block in custom:
            _w(parts, block)
        _w(parts, "")


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate Tiltfile from JSON config")
    parser.add_argument("--config", "-c", required=True, help="JSON config file path")
    parser.add_argument(
        "--all-suites", action="store_true", help="Generate Tiltfile for all suites"
    )
    args = parser.parse_args()

    import json
    from pathlib import Path

    with Path(args.config).open() as f:
        config = json.load(f)

    result = generate_tiltfile(config)
    print(result, end="")


if __name__ == "__main__":
    main()
