
// Auto-generated by BRRTRouter

use serde::{ Deserialize, Serialize };
use crate::brrtrouter::typed::TypedHandlerRequest;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    // Parameters and body fields
    pub name: String,
    
    }

#[derive(Debug, Serialize)]
pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    
    }

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::add_pet::handle(req)
}