
// Auto-generated by BRRTRouter

use serde::{ Deserialize, Serialize };
use crate::brrtrouter::typed::{ TypedHandlerRequest, TypedHandlerFor };

#[derive(Debug, Deserialize)]
pub struct Request {
    // Parameters and body fields
    }

#[derive(Debug, Serialize)]
pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feature_flags: Option<serde_json::Value>,
    
    }

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::admin_settings::handle(req)
}