// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Generated from: OpenAPI specification
// Template: handler.rs.txt
// Generation time: 2025-07-15 06:20:56 UTC

#![allow(unused_imports)]

use crate::brrtrouter::dispatcher::HandlerRequest;
use crate::brrtrouter::server::request::decode_param_value;
use crate::brrtrouter::spec::ParameterStyle;
use crate::brrtrouter::typed::TypedHandlerRequest;
use anyhow::anyhow;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

/// Request structure for get_item handler
///
/// This structure represents the complete request parameters and body
/// as defined in the OpenAPI specification.
#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    pub id: String,
}

/// Response structure for get_item handler
///
/// This structure represents the response format as defined
/// in the OpenAPI specification.
#[derive(Debug, Serialize)]

pub struct Response {
    pub category: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub in_stock: Option<bool>,

    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stock_quantity: Option<i32>,
}

/// Parameter extraction implementation with enhanced validation
impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        // Extract parameters with proper validation

        if let Some(v) = req.path_params.get("id") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"format":"uuid","type":"string"})),
                None,
                None,
            );

            data_map.insert("id".to_string(), decoded_value);
        } else {
            return Err(anyhow!("Missing required parameter 'id'"));
        }

        // Extract request body if present
        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        // Convert to strongly typed request structure
        serde_json::from_value(Value::Object(data_map))
            .map_err(|e| anyhow!("Failed to parse request parameters: {}", e))
    }
}

/// Main handler function that delegates to the controller
///
/// This function is called by the BRRTRouter dispatcher and handles
/// the conversion between the raw request and the typed request structure.
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_item::handle(req)
}
