// Auto-generated by BRRTRouter
use crate::brrtrouter::dispatcher::HandlerRequest;
use crate::brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(rename = "color")]
    pub color: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "color")]
    pub color: Option<String>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.path_params.get("color") {
            data_map.insert(
                "color".to_string(),
                crate::brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"type":"string"})),
                    Some(crate::brrtrouter::spec::ParameterStyle::Label),
                    Some(false),
                ),
            );
        } else {
            return Err(anyhow::anyhow!("Missing required parameter 'color'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_label::handle(req)
}
