// Auto-generated by BRRTRouter
use crate::brrtrouter::dispatcher::HandlerRequest;
use crate::brrtrouter::typed::TypedHandlerRequest;
use anyhow::anyhow;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    pub id: String,
}

#[derive(Debug, Serialize)]
pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        fn convert(value: &str, schema: Option<&Value>) -> Value {
            if let Some(ty) = schema.and_then(|s| s.get("type").and_then(|v| v.as_str())) {
                match ty {
                    "integer" => value
                        .parse::<i64>()
                        .map(Value::from)
                        .unwrap_or_else(|_| Value::String(value.to_string())),
                    "number" => value
                        .parse::<f64>()
                        .map(Value::from)
                        .unwrap_or_else(|_| Value::String(value.to_string())),
                    "boolean" => value
                        .parse::<bool>()
                        .map(Value::from)
                        .unwrap_or_else(|_| Value::String(value.to_string())),
                    _ => Value::String(value.to_string()),
                }
            } else {
                Value::String(value.to_string())
            }
        }

        let mut data_map = Map::new();

        if let Some(v) = req.path_params.get("id") {
            data_map.insert(
                "id".to_string(),
                convert(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                ),
            );
        } else {
            return Err(anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_item::handle(req)
}
