
// Auto-generated by BRRTRouter
use serde::{Deserialize, Serialize};
use crate::brrtrouter::typed::TypedHandlerRequest;


#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    pub user_id: String,
    
    pub post_id: String,
    
    }

#[derive(Debug, Serialize)]
pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    
    }

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_post::handle(req)
}