// Auto-generated by BRRTRouter
use crate::handlers::types::MedicalRecord;
use crate::handlers::types::PetOwner;
use crate::handlers::types::Photo;
use anyhow::anyhow;
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::server::request::decode_param_value;
use brrtrouter::spec::ParameterStyle;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub include: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub x_request_id: Option<String>,
}

#[derive(Debug, Serialize)]

pub struct Response {
    pub age: i32,

    pub breed: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,

    pub id: i32,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub medical_records: Option<Vec<MedicalRecord>>,

    pub name: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner: Option<PetOwner>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub photos: Option<Vec<Photo>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,

    pub tags: Vec<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,

    pub vaccinated: bool,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.path_params.get("id") {
            data_map.insert(
                "id".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"pattern":"^[0-9]+$","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow!("Missing required parameter 'id'"));
        }

        if let Some(v) = req.query_params.get("include") {
            data_map.insert(
                "include".to_string(),
                decode_param_value(
                    v,Some(&serde_json::json!({"items":{"enum":["owner","medical_records","photos"],"type":"string"},"type":"array"})),Some(ParameterStyle::Form ),Some(false),
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.headers.get("x_request_id") {
            data_map.insert(
                "x_request_id".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    match crate::controllers::get_pet::handle(req) {
        Ok(response) => response,
        Err(validation_error) => panic!("Controller validation error: {:?}", validation_error),
    }
}
