// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Generated from: OpenAPI specification
// Template: handler.rs.txt
// Generation time: 2025-07-15 12:05:24 UTC

#![allow(unused_imports)]

use crate::handlers::types::Pet;
use anyhow::anyhow;
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::server::request::decode_param_value;
use brrtrouter::spec::ParameterStyle;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::convert::TryFrom;

/// Request structure for list_pets handler
///
/// This structure represents the complete request parameters and body
/// as defined in the OpenAPI specification.
#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub breed: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub age_min: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub age_max: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vaccinated: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x_request_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accept_language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

/// Response structure for list_pets handler
///
/// This structure represents the response format as defined
/// in the OpenAPI specification.
#[derive(Debug, Serialize)]

pub struct Response(pub Vec<Pet>);

/// Parameter extraction implementation with enhanced validation
impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        let mut data_map = Map::new();

        // Extract parameters with proper validation

        if let Some(v) = req.query_params.get("limit") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"default":10,"maximum":100,"minimum":1,"type":"integer"})),
                None,
                None,
            );

            data_map.insert("limit".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.query_params.get("offset") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"default":0,"minimum":0,"type":"integer"})),
                None,
                None,
            );

            data_map.insert("offset".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.query_params.get("breed") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"maxLength":50,"minLength":2,"type":"string"})),
                None,
                None,
            );

            data_map.insert("breed".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.query_params.get("age_min") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"maximum":30,"minimum":0,"type":"integer"})),
                None,
                None,
            );

            data_map.insert("age_min".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.query_params.get("age_max") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"maximum":30,"minimum":0,"type":"integer"})),
                None,
                None,
            );

            data_map.insert("age_max".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.query_params.get("vaccinated") {
            let decoded_value =
                decode_param_value(v, Some(&serde_json::json!({"type":"boolean"})), None, None);

            data_map.insert("vaccinated".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.query_params.get("sort") {
            let decoded_value = decode_param_value(
                v,
                Some(
                    &serde_json::json!({"default":"name","enum":["name","age","breed","-name","-age","-breed"],"type":"string"}),
                ),
                None,
                None,
            );

            data_map.insert("sort".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.query_params.get("tags") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"items":{"type":"string"},"type":"array"})),
                Some(ParameterStyle::Form),
                Some(false),
            );

            data_map.insert("tags".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.headers.get("x_request_id") {
            let decoded_value = decode_param_value(
                v,
                Some(&serde_json::json!({"format":"uuid","type":"string"})),
                None,
                None,
            );

            data_map.insert("x_request_id".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.headers.get("accept_language") {
            let decoded_value = decode_param_value(
                v,
                Some(
                    &serde_json::json!({"default":"en","enum":["en","es","fr","de"],"type":"string"}),
                ),
                None,
                None,
            );

            data_map.insert("accept_language".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        if let Some(v) = req.cookies.get("session_id") {
            let decoded_value =
                decode_param_value(v, Some(&serde_json::json!({"type":"string"})), None, None);

            data_map.insert("session_id".to_string(), decoded_value);
        } else {

            // Optional parameter - skip if not present
        }

        // Extract request body if present
        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        // Convert to strongly typed request structure
        serde_json::from_value(Value::Object(data_map))
            .map_err(|e| anyhow!("Failed to parse request parameters: {}", e))
    }
}

/// Main handler function that delegates to the controller
///
/// This function is called by the BRRTRouter dispatcher and handles
/// the conversion between the raw request and the typed request structure.
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::list_pets::handle(req)
}
