
// Auto-generated by BRRTRouter

use serde::{ Deserialize, Serialize };
use serde_json::Value;
use crate::brrtrouter::dispatcher::HandlerRequest;
use crate::brrtrouter::typed::{ TypedHandlerRequest, TypedHandlerResponse, TypedHandlerFor };

use crate::handlers::types::Post;
#[derive(Debug, Deserialize)]
pub struct Request {
    pub user_id: String,
    }

#[derive(Debug, Serialize)]
pub struct Response {
    pub items: Vec<Post>,
    
    }

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::list_user_posts::handle(req)
}
