// Auto-generated by BRRTRouter
use crate::handlers::types::Pet;
use anyhow::anyhow;
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::server::request::decode_param_value;
use brrtrouter::spec::ParameterStyle;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub breed: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub age_min: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub age_max: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub vaccinated: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub x_request_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub accept_language: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

#[derive(Debug, Serialize)]

pub struct Response(pub Vec<Pet>);

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.query_params.get("limit") {
            data_map.insert(
                "limit".to_string(),
                decode_param_value(
                    v,Some(&serde_json::json!({"default":10,"maximum":100,"minimum":1,"type":"integer"})),None,None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("offset") {
            data_map.insert(
                "offset".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"default":0,"minimum":0,"type":"integer"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("breed") {
            data_map.insert(
                "breed".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"maxLength":50,"minLength":2,"type":"string"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("age_min") {
            data_map.insert(
                "age_min".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"maximum":30,"minimum":0,"type":"integer"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("age_max") {
            data_map.insert(
                "age_max".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"maximum":30,"minimum":0,"type":"integer"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("vaccinated") {
            data_map.insert(
                "vaccinated".to_string(),
                decode_param_value(v, Some(&serde_json::json!({"type":"boolean"})), None, None),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("sort") {
            data_map.insert(
                "sort".to_string(),
                decode_param_value(
                    v,Some(&serde_json::json!({"default":"name","enum":["name","age","breed","-name","-age","-breed"],"type":"string"})),None,None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("tags") {
            data_map.insert(
                "tags".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"items":{"type":"string"},"type":"array"})),
                    Some(ParameterStyle::Form),
                    Some(false),
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.headers.get("x_request_id") {
            data_map.insert(
                "x_request_id".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.headers.get("accept_language") {
            data_map.insert(
                "accept_language".to_string(),
                decode_param_value(
                    v,Some(&serde_json::json!({"default":"en","enum":["en","es","fr","de"],"type":"string"})),None,None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.cookies.get("session_id") {
            data_map.insert(
                "session_id".to_string(),
                decode_param_value(v, Some(&serde_json::json!({"type":"string"})), None, None),
            );
        } else {

            // optional parameter
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    match crate::controllers::list_pets::handle(req) {
        Ok(response) => response,
        Err(validation_error) => panic!("Controller validation error: {:?}", validation_error),
    }
}
