// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Generated from: OpenAPI specification
// Template: handler.rs.txt
// Generation time: 2025-07-15 11:20:03 UTC

#![allow(unused_imports)]

use crate::handlers::types::User;
use anyhow::anyhow;
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::server::request::decode_param_value;
use brrtrouter::spec::ParameterStyle;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::convert::TryFrom;

/// Request structure for list_users handler
///
/// This structure represents the complete request parameters and body
/// as defined in the OpenAPI specification.
#[derive(Debug, Deserialize, Serialize)]
pub struct Request {}

/// Response structure for list_users handler
///
/// This structure represents the response format as defined
/// in the OpenAPI specification.
#[derive(Debug, Serialize)]

pub struct Response {
    pub page: i32,

    pub per_page: i32,

    pub total: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_pages: Option<i32>,

    pub users: Vec<User>,
}

/// Parameter extraction implementation with enhanced validation
impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        let mut data_map = Map::new();

        // Extract parameters with proper validation

        // Extract request body if present
        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        // Convert to strongly typed request structure
        serde_json::from_value(Value::Object(data_map))
            .map_err(|e| anyhow!("Failed to parse request parameters: {}", e))
    }
}

/// Main handler function that delegates to the controller
///
/// This function is called by the BRRTRouter dispatcher and handles
/// the conversion between the raw request and the typed request structure.
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::list_users::handle(req)
}
