// Auto-generated by BRRTRouter
use anyhow::anyhow;
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::server::request::decode_param_value;
use brrtrouter::spec::ParameterStyle;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    pub category: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    pub name: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub stock_quantity: Option<i32>,

    pub id: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    pub category: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub in_stock: Option<bool>,

    pub name: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub stock_quantity: Option<i32>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.path_params.get("id") {
            data_map.insert(
                "id".to_string(),
                decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    match crate::controllers::post_item::handle(req) {
        Ok(response) => response,
        Err(validation_error) => panic!("Controller validation error: {:?}", validation_error),
    }
}
