// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use crate::handlers::types::Item;
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "filters")]
    pub filters: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "X-Trace-Id")]
    pub X_Trace_Id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "session")]
    pub session: Option<String>,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "results")]
    pub results: Option<Vec<Item>>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.query_params.get("tags") {
            data_map.insert(
                "tags".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"items":{"type":"string"},"type":"array"})),
                    Some(brrtrouter::spec::ParameterStyle::PipeDelimited),
                    Some(false),
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.query_params.get("filters") {
            data_map.insert(
                "filters".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,Some(&serde_json::json!({"additionalProperties":{"type":"string"},"type":"object"})),Some(brrtrouter::spec::ParameterStyle::DeepObject ),Some(true),
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.headers.get("x-trace-id") {
            data_map.insert(
                "X-Trace-Id".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(v) = req.cookies.get("session") {
            data_map.insert(
                "session".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"type":"string"})),
                    None,
                    None,
                ),
            );
        } else {

            // optional parameter
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::search::handle(req)
}
