// Auto-generated by BRRTRouter
use anyhow::anyhow;
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::server::request::decode_param_value;
use brrtrouter::spec::ParameterStyle;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {}

#[derive(Debug, Serialize)]

pub struct Response(pub String);

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    match crate::controllers::stream_events::handle(req) {
        Ok(response) => response,
        Err(validation_error) => panic!("Controller validation error: {:?}", validation_error),
    }
}
