// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Generated from: OpenAPI specification
// Template: handler_types.rs.txt
// Generation time: 2025-07-15 05:44:43 UTC

use serde::{Deserialize, Serialize};

/// AddPetRequest type definition
///
/// Generated from OpenAPI schema: AddPetRequest
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AddPetRequest {
    /// name field
    pub name: String,
}

/// AddPetResponse type definition
///
/// Generated from OpenAPI schema: AddPetResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AddPetResponse {
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// status field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

/// AdminSettings type definition
///
/// Generated from OpenAPI schema: AdminSettings
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AdminSettings {
    /// feature_flags field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feature_flags: Option<serde_json::Value>,
}

/// AdminSettingsResponse type definition
///
/// Generated from OpenAPI schema: AdminSettingsResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AdminSettingsResponse {
    /// feature_flags field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feature_flags: Option<serde_json::Value>,
}

/// CreateItemRequest type definition
///
/// Generated from OpenAPI schema: CreateItemRequest
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateItemRequest {
    /// name field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// CreatePetRequest type definition
///
/// Generated from OpenAPI schema: CreatePetRequest
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreatePetRequest {
    /// name field
    pub name: String,
}

/// GetItemResponse type definition
///
/// Generated from OpenAPI schema: GetItemResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetItemResponse {
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// name field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// GetPetResponse type definition
///
/// Generated from OpenAPI schema: GetPetResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetPetResponse {
    /// age field
    pub age: i32,
    /// breed field
    pub breed: String,
    /// id field
    pub id: i32,
    /// name field
    pub name: String,
    /// tags field
    pub tags: Vec<String>,
    /// vaccinated field
    pub vaccinated: bool,
}

/// GetPostResponse type definition
///
/// Generated from OpenAPI schema: GetPostResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetPostResponse {
    /// body field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// title field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// GetUserResponse type definition
///
/// Generated from OpenAPI schema: GetUserResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetUserResponse {
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// name field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Item type definition
///
/// Generated from OpenAPI schema: Item
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Item {
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// name field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// ListPetsResponse type definition
///
/// Generated from OpenAPI schema: ListPetsResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListPetsResponse {
    /// items field
    pub items: Vec<Pet>,
}

/// ListUserPostsResponse type definition
///
/// Generated from OpenAPI schema: ListUserPostsResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListUserPostsResponse {
    /// items field
    pub items: Vec<Post>,
}

/// ListUsersResponse type definition
///
/// Generated from OpenAPI schema: ListUsersResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListUsersResponse {
    /// users field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<User>>,
}

/// Pet type definition
///
/// Generated from OpenAPI schema: Pet
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Pet {
    /// age field
    pub age: i32,
    /// breed field
    pub breed: String,
    /// id field
    pub id: i32,
    /// name field
    pub name: String,
    /// tags field
    pub tags: Vec<String>,
    /// vaccinated field
    pub vaccinated: bool,
}

/// PetCreationResponse type definition
///
/// Generated from OpenAPI schema: PetCreationResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct PetCreationResponse {
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// status field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

/// Post type definition
///
/// Generated from OpenAPI schema: Post
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Post {
    /// body field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// title field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// PostItemRequest type definition
///
/// Generated from OpenAPI schema: PostItemRequest
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct PostItemRequest {
    /// name field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// PostItemResponse type definition
///
/// Generated from OpenAPI schema: PostItemResponse
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct PostItemResponse {
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// name field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// User type definition
///
/// Generated from OpenAPI schema: User
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct User {
    /// id field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// name field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// UserList type definition
///
/// Generated from OpenAPI schema: UserList
/// This type represents the structure defined in the OpenAPI specification.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UserList {
    /// users field
    #[serde(skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<User>>,
}
