// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AddPetRequest {
    pub name: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AddPetResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AdminSettings {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feature_flags: Option<serde_json::Value>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AdminSettingsResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feature_flags: Option<serde_json::Value>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Cat {
    pub meow: bool,

    #[serde(rename = "type")]
    pub r#type: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateItemRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreatePetRequest {
    pub name: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Dog {
    pub bark: bool,

    #[serde(rename = "type")]
    pub r#type: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct DownloadFileResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetItemResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetLabelResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetMatrixResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coords: Option<Vec<i32>>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetPetResponse {
    pub age: i32,

    pub breed: String,

    pub id: i32,

    pub name: String,

    pub tags: Vec<String>,

    pub vaccinated: bool,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetPostResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,

    pub body: String,

    pub id: String,

    pub title: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetUserResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,

    pub id: String,

    pub name: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct HeadUserResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exists: Option<bool>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Item {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListPetsResponse {
    pub items: Vec<Pet>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListUserPostsResponse {
    pub items: Vec<Post>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListUsersResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<User>>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct OptionsUserResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allow: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Pet {
    pub age: i32,

    pub breed: String,

    pub id: i32,

    pub name: String,

    pub tags: Vec<String>,

    pub vaccinated: bool,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct PetCreationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Post {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,

    pub body: String,

    pub id: String,

    pub title: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct PostItemRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct PostItemResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ProblemDetails {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,

    #[serde(rename = "type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct RegisterWebhookRequest {
    pub url: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct RegisterWebhookResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct SearchResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<Item>>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct SecureEndpointResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct SubmitFormResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ok: Option<bool>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UploadFileResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct User {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,

    pub id: String,

    pub name: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UserList {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<User>>,
}
