// Auto-generated by BRRTRouter

pub mod add_pet;

pub mod admin_settings;

pub mod get_item;

pub mod get_pet;

pub mod get_post;

pub mod get_user;

pub mod list_pets;

pub mod list_user_posts;

pub mod list_users;

pub mod post_item;
