openapi: 3.1.0
info:
  title: Pet Store
  version: "1.0.0"
paths:
  /pets:
    get:
      summary: List pets
      x-handler-list: list_pets
      responses:
        "200":
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required: [ id, name, breed, age, vaccinated, tags ]
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    breed:
                      type: string
                    age:
                      type: integer
                    vaccinated:
                      type: boolean
                    tags:
                      type: array
                      items:
                        type: string

    post:
      summary: Add a pet
      x-handler-add: add_pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ name ]
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Pet added
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
  /pets/{id}:
    get:
      summary: Get a specific pet
      x-handler-get: get_pet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A pet
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
  /users:
    get:
      summary: List users
      x-handler-list: list_users
      responses:
        "200": { description: OK }

  /users/{user_id}:
    get:
      summary: Get user by ID
      x-handler-get: get_user
      parameters:
        - name: user_id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }

  /users/{user_id}/posts:
    get:
      summary: List posts by user
      x-handler-list: list_user_posts
      parameters:
        - name: user_id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }

  /users/{user_id}/posts/{post_id}:
    get:
      summary: Get specific post
      x-handler-get: get_post
      parameters:
        - name: user_id
          in: path
          required: true
          schema: { type: string }
        - name: post_id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }

  /admin/settings:
    get:
      summary: Admin settings
      x-handler-admin: admin_settings
      responses:
        "200": { description: OK }
  /items/{id}:
    get:
      x-handler-get: get_item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Get an item
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string

    post:
      summary: Update or create item by ID
      x-handler-post: post_item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Item upserted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
