
// Auto-generated by BRRTRouter

use serde::{ Deserialize, Serialize };
use serde_json::Value;
use crate::dispatcher::HandlerRequest;
use crate::typed::{ TypedHandlerRequest, TypedHandlerResponse };

#[derive(Debug, Deserialize)]
pub struct Request {
    
}

#[derive(Debug, Serialize)]
pub struct Response {
    
    pub age: i32,
    
    
    pub breed: String,
    
    
    pub id: i32,
    
    
    pub name: String,
    
    
    pub tags: Vec<Value>,
    
    
    pub vaccinated: bool,
    
    
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::list_pets::handle(req)
}

impl From<HandlerRequest> for TypedHandlerRequest<Request> {
    fn from(_req: HandlerRequest) -> Self {
        // TODO: convert HandlerRequest to TypedHandlerRequest<Request>
        unimplemented!()
    }
}

impl From<TypedHandlerRequest<Request>> for HandlerRequest {
    fn from(_req: TypedHandlerRequest<Request>) -> Self {
        // TODO: convert TypedHandlerRequest<Request> to HandlerRequest
        unimplemented!()
    }
}