
// Auto-generated by BRRTRouter
use serde::{Deserialize, Serialize};
use crate::brrtrouter::typed::TypedHandlerRequest;
use crate::brrtrouter::dispatcher::HandlerRequest;
use std::convert::TryFrom;


#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    
    #[serde(rename = "user_id")]
    pub user_id: String,
    
    
    #[serde(rename = "post_id")]
    pub post_id: String,
    
    }

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")] 
    #[serde(rename = "author_id")]
    
    pub author_id: Option<String>,
    
    
    #[serde(rename = "body")]
    pub body: String,
    
    
    #[serde(rename = "id")]
    pub id: String,
    
    
    #[serde(rename = "title")]
    pub title: String,
    
    }


impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        
        
        if let Some(v) = req.path_params.get("user_id") {
        
            data_map.insert(
                "user_id".to_string(),
                crate::brrtrouter::server::request::decode_param_value(
                    v,Some(&serde_json::json!({"type":"string"})),None,None,
                ),
            );
        } else {
            
            return Err(anyhow::anyhow!("Missing required parameter 'user_id'"));
            
        }
        
        
        if let Some(v) = req.path_params.get("post_id") {
        
            data_map.insert(
                "post_id".to_string(),
                crate::brrtrouter::server::request::decode_param_value(
                    v,Some(&serde_json::json!({"type":"string"})),None,None,
                ),
            );
        } else {
            
            return Err(anyhow::anyhow!("Missing required parameter 'post_id'"));
            
        }
        

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map { data_map.insert(k, v); }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_post::handle(req)
}