// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Template: registry.rs.txt

use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;

// Import the controller types
use crate::controllers::add_pet::AddPetController;
use crate::controllers::admin_settings::AdminSettingsController;
use crate::controllers::get_item::GetItemController;
use crate::controllers::get_pet::GetPetController;
use crate::controllers::get_post::GetPostController;
use crate::controllers::get_user::GetUserController;
use crate::controllers::list_pets::ListPetsController;
use crate::controllers::list_user_posts::ListUserPostsController;
use crate::controllers::list_users::ListUsersController;
use crate::controllers::post_item::PostItemController;
use crate::controllers::stream_events::StreamEventsController;
/// Register all predefined handlers with the dispatcher
///
/// This function provides a convenient way to register all handlers
/// that are defined at compile time. Use this for static handler registration.
///
/// # Safety
/// This function is unsafe because it registers handlers with the dispatcher
/// which may involve raw pointer operations or other unsafe operations.
pub unsafe fn register_all(dispatcher: &mut Dispatcher) {
    dispatcher.register_typed("admin_settings", AdminSettingsController);
    dispatcher.register_typed("stream_events", StreamEventsController);
    dispatcher.register_typed("get_item", GetItemController);
    dispatcher.register_typed("post_item", PostItemController);
    dispatcher.register_typed("list_pets", ListPetsController);
    dispatcher.register_typed("add_pet", AddPetController);
    dispatcher.register_typed("get_pet", GetPetController);
    dispatcher.register_typed("list_users", ListUsersController);
    dispatcher.register_typed("get_user", GetUserController);
    dispatcher.register_typed("list_user_posts", ListUserPostsController);
    dispatcher.register_typed("get_post", GetPostController);
}

/// Register all routes from OpenAPI specification with the dispatcher
///
/// This function processes the routes loaded from the OpenAPI specification
/// and registers the corresponding handlers with the dispatcher. This version
/// uses idempotent registration to support safe hot reloading.
///
/// # Safety
/// This function is unsafe because it registers handlers with the dispatcher
/// which may involve raw pointer operations or other unsafe operations.
pub unsafe fn register_from_spec(dispatcher: &mut Dispatcher, _routes: &[RouteMeta]) {
    dispatcher.register_or_update_typed("admin_settings", AdminSettingsController);
    dispatcher.register_or_update_typed("stream_events", StreamEventsController);
    dispatcher.register_or_update_typed("get_item", GetItemController);
    dispatcher.register_or_update_typed("post_item", PostItemController);
    dispatcher.register_or_update_typed("list_pets", ListPetsController);
    dispatcher.register_or_update_typed("add_pet", AddPetController);
    dispatcher.register_or_update_typed("get_pet", GetPetController);
    dispatcher.register_or_update_typed("list_users", ListUsersController);
    dispatcher.register_or_update_typed("get_user", GetUserController);
    dispatcher.register_or_update_typed("list_user_posts", ListUserPostsController);
    dispatcher.register_or_update_typed("get_post", GetPostController);
}

/// Register or update a single route by name. This is idempotent and safe for hot reloading.
///
/// # Safety
/// This function is unsafe because it registers handlers with the dispatcher
/// which may involve raw pointer operations or other unsafe operations.
pub unsafe fn register_or_update_route(dispatcher: &mut Dispatcher, route_name: &str) {
    match route_name {
        "admin_settings" => {
            dispatcher.register_or_update_typed("admin_settings", AdminSettingsController);
        }
        "stream_events" => {
            dispatcher.register_or_update_typed("stream_events", StreamEventsController);
        }
        "get_item" => {
            dispatcher.register_or_update_typed("get_item", GetItemController);
        }
        "post_item" => {
            dispatcher.register_or_update_typed("post_item", PostItemController);
        }
        "list_pets" => {
            dispatcher.register_or_update_typed("list_pets", ListPetsController);
        }
        "add_pet" => {
            dispatcher.register_or_update_typed("add_pet", AddPetController);
        }
        "get_pet" => {
            dispatcher.register_or_update_typed("get_pet", GetPetController);
        }
        "list_users" => {
            dispatcher.register_or_update_typed("list_users", ListUsersController);
        }
        "get_user" => {
            dispatcher.register_or_update_typed("get_user", GetUserController);
        }
        "list_user_posts" => {
            dispatcher.register_or_update_typed("list_user_posts", ListUserPostsController);
        }
        "get_post" => {
            dispatcher.register_or_update_typed("get_post", GetPostController);
        }
        _ => {
            eprintln!("⚠️  Unknown route name for registration: {}", route_name);
        }
    }
}
