// ⚠️ WARNING: This file is auto-generated by BRRTRouter for the **gen** crate
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next `brrtrouter-gen generate`
// ⚠️ To change API shape, edit the OpenAPI spec and regenerate the gen crate
// ⚠️ Mock/example controllers live in gen/src/controllers/ — they are NOT business logic
//
// ADR 0001 Layer 1: `register_from_spec` wires **gen mock controllers** for every route.
// Real implementations live in the sibling **impl** crate; see `impl_registry.rs.txt` →
// `<service>_impl/src/impl_registry.rs` (`register_impl`), which overrides selected routes.

use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed_with_stack_size_and_name;

/// Register all gen handlers statically (legacy; prefer `register_from_spec`).
///
/// # Safety
/// Spawns handler coroutines. Callers must ensure coroutine runtime is set up.
#[allow(dead_code)]
pub unsafe fn register_all(dispatcher: &mut Dispatcher) {
    dispatcher.register_typed_with_stack_size(
        "admin_settings",
        crate::controllers::admin_settings::AdminSettingsController,
        16384,
    );

    dispatcher.register_typed_with_stack_size(
        "download_file",
        crate::controllers::download_file::DownloadFileController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "stream_events",
        crate::controllers::stream_events::StreamEventsController,
        24576,
    );

    dispatcher.register_typed_with_stack_size(
        "submit_form",
        crate::controllers::submit_form::SubmitFormController,
        16384,
    );

    dispatcher.register_typed_with_stack_size(
        "get_item",
        crate::controllers::get_item::GetItemController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "post_item",
        crate::controllers::post_item::PostItemController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "get_label",
        crate::controllers::get_label::GetLabelController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "get_matrix",
        crate::controllers::get_matrix::GetMatrixController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "list_pets",
        crate::controllers::list_pets::ListPetsController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "add_pet",
        crate::controllers::add_pet::AddPetController,
        16384,
    );

    dispatcher.register_typed_with_stack_size(
        "get_pet",
        crate::controllers::get_pet::GetPetController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "search",
        crate::controllers::search::SearchController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "secure_endpoint",
        crate::controllers::secure_endpoint::SecureEndpointController,
        16384,
    );

    dispatcher.register_typed_with_stack_size(
        "upload_file",
        crate::controllers::upload_file::UploadFileController,
        16384,
    );

    dispatcher.register_typed_with_stack_size(
        "list_users",
        crate::controllers::list_users::ListUsersController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "get_user",
        crate::controllers::get_user::GetUserController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "delete_user",
        crate::controllers::delete_user::DeleteUserController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "options_user",
        crate::controllers::options_user::OptionsUserController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "head_user",
        crate::controllers::head_user::HeadUserController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "list_user_posts",
        crate::controllers::list_user_posts::ListUserPostsController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "get_post",
        crate::controllers::get_post::GetPostController,
        20480,
    );

    dispatcher.register_typed_with_stack_size(
        "register_webhook",
        crate::controllers::register_webhook::RegisterWebhookController,
        16384,
    );
}

/// Register gen mock/proxy controllers for routes from the OpenAPI spec (ADR 0001 Layer 1).
///
/// Clears existing handler registrations before wiring routes. In a gen+impl service,
/// call this first, then `<service>_impl::impl_registry::register_impl` to override
/// selected handlers with real business logic.
///
/// # Safety
/// Spawns handler coroutines. Callers must ensure coroutine runtime is set up.
pub unsafe fn register_from_spec(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    dispatcher.handlers.clear();
    dispatcher.worker_pools.clear();

    for route in routes {
        match route.handler_name.as_ref() {
            "admin_settings" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::admin_settings::AdminSettingsController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "download_file" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::download_file::DownloadFileController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "stream_events" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::stream_events::StreamEventsController,
                    24576,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "submit_form" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::submit_form::SubmitFormController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_item" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_item::GetItemController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "post_item" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::post_item::PostItemController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_label" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_label::GetLabelController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_matrix" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_matrix::GetMatrixController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_pets" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_pets::ListPetsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "add_pet" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::add_pet::AddPetController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_pet" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_pet::GetPetController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "search" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::search::SearchController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "secure_endpoint" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::secure_endpoint::SecureEndpointController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "upload_file" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::upload_file::UploadFileController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_users" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_users::ListUsersController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_user" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_user::GetUserController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_user" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_user::DeleteUserController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "options_user" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::options_user::OptionsUserController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "head_user" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::head_user::HeadUserController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_user_posts" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_user_posts::ListUserPostsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_post" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_post::GetPostController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "register_webhook" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::register_webhook::RegisterWebhookController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }

            _ => {}
        }
    }
}
