apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: brrtrouter-dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      # Scrape Pet Store metrics
      - job_name: 'petstore'
        static_configs:
          - targets: ['petstore:8080']
            labels:
              app: 'petstore'
              environment: 'dev'
      
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: brrtrouter-dev
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # Init container to fix permissions on persistent volume
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /prometheus
              chmod -R 777 /prometheus
              chown -R 65534:65534 /prometheus
          volumeMounts:
            - name: storage
              mountPath: /prometheus
          securityContext:
            runAsUser: 0
      containers:
        - name: prometheus
          image: prom/prometheus:v2.48.0
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: storage
              mountPath: /prometheus
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            runAsNonRoot: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: storage
          persistentVolumeClaim:
            claimName: prometheus-storage
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: brrtrouter-dev
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: web
      nodePort: 30090
      protocol: TCP
      name: web
  selector:
    app: prometheus

