// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Generated from: OpenAPI specification
// Template: controller.rs.txt
// Generation time: 2025-07-15 06:05:06 UTC

#![allow(unused_imports)]

use crate::brrtrouter::typed::TypedHandlerRequest;
use crate::handlers::list_users::{Request, Response};
use brrtrouter_macros::handler;

use crate::handlers::types::User;

/// Controller implementation for list_users
///
/// This is where you implement your business logic. The controller receives
/// a validated request and should return an appropriate response.
///
/// ## Implementation Notes
/// - The request has already been validated against the OpenAPI specification
/// - All required parameters are guaranteed to be present
/// - Parameter types have been validated and converted
/// - You can focus on implementing the business logic
/// ## Example Response
/// ```json
///         // {
//   "users": [
//     {
//       "id": "abc-123",
//       "name": "John"
//     },
//     {
//       "id": "def-456",
//       "name": "Jane"
//     }
//   ]
// }
/// ```

#[handler(ListUsersController)]
pub fn handle(_req: TypedHandlerRequest<Request>) -> Response {
    // TODO: Implement your business logic here
    //
    // The request contains validated parameters and body data.
    // You should:
    // 1. Extract necessary data from the request
    // 2. Perform your business operations
    // 3. Return an appropriate response
    //
    // Example implementation:
    // let result = your_business_logic(&req.data);
    // match result {
    //     Ok(data) => Response { /* populate fields */ },
    //     Err(e) => panic!("Handle error appropriately"),
    // }

    // Object response - replace with your actual data
    Response {
        users: Some(vec![
            serde_json::from_value::<User>(serde_json::json!({"id":"abc-123","name":"John"}))
                .unwrap(),
            serde_json::from_value::<User>(serde_json::json!({"id":"def-456","name":"Jane"}))
                .unwrap(),
        ]), // TODO: Replace with actual value
    }
}

// TODO: Add any helper functions for your business logic here
