name: e2e-docker

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'tests/docker_integration_tests.rs'
      - 'examples/pet_store/**'
      - 'src/**'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install musl target (optional)
        run: rustup target add x86_64-unknown-linux-musl || true

      - name: Build e2e Docker image
        run: docker build --no-cache -t brrtrouter-petstore:e2e .

      - name: Run e2e test
        run: cargo test --test docker_integration_tests -- --ignored

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-e2e
          path: target/e2e/junit-e2e.xml
