// ⚠️  AUTO-GENERATED CODE - DO NOT EDIT
// This file is generated by BRRTRouter from OpenAPI specifications.
// Manual changes will be overwritten during code generation.
// To modify this code, edit the corresponding template in templates/
// or update the OpenAPI specification.
//
// Generated from: OpenAPI specification
// Template: handler.rs.txt
// Generation time: 2025-07-15 08:27:16 UTC

#![allow(unused_imports)]

use serde::{Deserialize, Serialize};
use crate::brrtrouter::typed::TypedHandlerRequest;
use crate::brrtrouter::dispatcher::HandlerRequest;
use crate::brrtrouter::server::request::decode_param_value;
use crate::brrtrouter::spec::ParameterStyle;
use anyhow::anyhow;
use std::convert::TryFrom;


/// Request structure for get_post handler
/// 
/// This structure represents the complete request parameters and body
/// as defined in the OpenAPI specification.
#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    
    pub user_id: String,
    
    pub post_id: String,
    }

/// Response structure for get_post handler
/// 
/// This structure represents the response format as defined
/// in the OpenAPI specification.
#[derive(Debug, Serialize)]

pub struct Response {
    
    pub author_id: String,
    
    pub body: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub view_count: Option<i32>,
    }


/// Parameter extraction implementation with enhanced validation
impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        // Extract parameters with proper validation
        
        
        if let Some(v) = req.path_params.get("user_id") {
        
            let decoded_value = decode_param_value(
                v,Some(&serde_json::json!({"type":"string"})),None,None,
            );
            
            data_map.insert("user_id".to_string(), decoded_value);
        } else {
            
            return Err(anyhow!("Missing required parameter 'user_id'"));
            
        }
        
        
        if let Some(v) = req.path_params.get("post_id") {
        
            let decoded_value = decode_param_value(
                v,Some(&serde_json::json!({"type":"string"})),None,None,
            );
            
            data_map.insert("post_id".to_string(), decoded_value);
        } else {
            
            return Err(anyhow!("Missing required parameter 'post_id'"));
            
        }
        

        // Extract request body if present
        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        // Convert to strongly typed request structure
        serde_json::from_value(Value::Object(data_map)).map_err(|e| {
            anyhow!("Failed to parse request parameters: {}", e)
        })
    }
}

/// Main handler function that delegates to the controller
/// 
/// This function is called by the BRRTRouter dispatcher and handles
/// the conversion between the raw request and the typed request structure.
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_post::handle(req)
}